name: "Check Links"
description: "Run a link check function for a repo"
runs:
  using: "composite"
  steps:
    - name: install-releaser
      uses: ./.github/actions/install-releaser

    - name: Cache checked links
      uses: actions/cache@v2
      with:
        path: ~/.cache/pytest-link-check
        key: ${{ runner.os }}-linkcheck-${{ hashFiles('**/*.md', '**/*.rst') }}-links
        restore-keys: |
          ${{ runner.os }}-linkcheck-

    - shell: bash
      id: check-links
      run: |
        set -eux
        python -m jupyter_releaser.actions.check_links
