name: "Check Links"
description: "Run a link check function for a repo"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: check-links
      run: |
        set -eux

        # Set up env variables
        export RH_REPOSITORY=${GITHUB_REPOSITORY}
        export RH_REF=${GITHUB_REF}

        if [ ! -z ${GITHUB_BASE_REF} ]; then
          echo "Using GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          export RH_BRANCH=${GITHUB_BASE_REF}
        else
          # e.g refs/head/foo or refs/tag/bar
          echo "Using GITHUB_REF: ${GITHUB_REF}"
          export RH_BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3-)
        fi

        # Install Jupyter Releaser from git unless we are testing Releaser itself
        if ! command -v jupyter-releaser &> /dev/null
        then
            pip install git+https://github.com/jupyter-server/jupyter_releaser.git
        fi

        jupyter-releaser prep-git
        jupyter-releaser check-links --force
