name: "Check Release"
description: "Run through a dry run release cycle"
inputs:
  token:
    description: "GitHub access token"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      id: draft-release
      run: |
        set -eux

        # Set up env variables
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_REPOSITORY=${GITHUB_REPOSITORY}
        export RH_CHANGELOG=${{ inputs.changelog }}
        export RH_DRY_RUN=true
        export RH_REF=${GITHUB_REF}

        if [ ! -z ${GITHUB_BASE_REF} ]; then
          echo "Using GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          export RH_BRANCH=${GITHUB_BASE_REF}
        else
          # e.g refs/head/foo or refs/tag/bar
          echo "Using GITHUB_REF: ${GITHUB_REF}"
          export RH_BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3)
        fi

        # Install Jupyter Releaser from git unless we are testing Releaser itself
        export RH_REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f 2)
        echo "repo name: ${RH_REPO_NAME}"
        if [ ${RH_REPO_NAME} !=  "jupyter_releaser" ]; then
           pip install git+https://github.com/jupyter-server/jupyter_releaser.git
        fi

        export RH_IS_CHECK_RELEASE=true

        # Draft Changelog
        python -m jupyter_releaser.actions.draft_changelog

        # Draft Release
        python -m jupyter_releaser.actions.draft_release

        # Publish Assets
        jupyter-releaser publish-assets --use-checkout-dir
