name: "Check Release"
description: "Run through a dry run release cycle"
inputs:
  token:
    description: "GitHub access token"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
    required: false
runs:
  using: "composite"
  steps:
    - name: install-releaser
      uses: ././github/actions/install-releaser

    - name: draft-changelog
      uses: ././github/actions/draft-changelog
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        changelog: ${{ inputs.changelog }}

    - name: draft-release
      uses: ././github/actions/draft-release
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        changelog: ${{ inputs.changelog }}

    - name: publish-release
      uses: ././github/actions/publish-release
      env:
        RH_IS_CHECK_RELEASE: "true"
      with:
        dry_run: true
        token: ${{ inputs.token }}
        relase_url: ${{ steps.draft-release.outputs.release_url }}
