name: Draft Changelog
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: true
      branch:
        description: The branch to target"
        required: true
      version_spec:
        description: "New Version Spec"
        required: true
      since:
        description: Use PRs with activity since this date or git reference
        required: false
      since_last_stable:
        description: Use PRs with activity since the last stable git tag
        required: false
jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Setup
        uses: ./.github/actions/common

      - name: Draft Changelog
        id: draft-changelog
        uses: ./.github/actions/draft-changelog
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          version_spec: ${{ github.event.inputs.version_spec }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: "** Next Step **"
        run: |
          echo "Review PR: ${{ steps.draft-changelog.outputs.pr_url }}"
