name: Draft Changelog
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: true
      branch:
        description: The branch to target"
        required: true
      version_spec:
        description: "New Version Spec"
        required: true
      since:
        description: Use PRs with activity since this date or git reference
        required: false
      since_last_stable:
        description: Use PRs with activity since the last stable git tag
        required: false
jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Upgrade packaging dependencies
        run: |
          pip install --upgrade pip setuptools wheel --user
      - name: Draft Changelog
        id: draft-changelog
        uses: jupyter-server/jupyter_releaser/.github/actions/draft-changelog@v1
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          version_spec: ${{ github.event.inputs.version_spec }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.intputs.since_last_stable }}
      - name: "** Next Step **"
        run: |
          echo "Review PR: ${{ steps.draft-changelog.outputs.pr_url }}"
