name: Generate Changelog
on:
  workflow_dispatch:
    inputs:
      target:
        description: Target Owner/Repo
        required: true
      branch:
        description: The branch or reference name to filter pull requests by
        required: true
      convert_to_rst:
        description: Whether to convert to RST
        required: false
      since:
        description: Use PRs with activity since this date or git reference
        required: false
      until:
        description: Use PRs with activity until this date or git reference
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Setup
        uses: ./.github/actions/common

      - name: Install the Extra Python dependencies
        run: |
          sudo apt-get install pandoc
          pip install pypandoc

      - name: Generate the Changelog
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export RH_BRANCH=${{ github.event.inputs.branch }}
          export RH_SINCE=${{ github.event.inputs.since }}
          export RH_REF=refs/heads/${RH_BRANCH}
          export RH_REPOSITORY=${{ github.event.inputs.target }}
          export RH_UNTIL=${{ github.event.inputs.until }}
          export RH_CONVERT_TO_RST=${{ github.event.inputs.convert_to_rst }}
          python -m jupyter_releaser.actions.generate-changelog
          cat CHANGELOG_ENTRY.md

      - uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG_ENTRY.md
