name: Publish Release
on:
  workflow_dispatch:
    inputs:
      release_url:
        description: "The URL of the draft GitHub release"
        required: true
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-pip-
      - name: Upgrade packaging dependencies
        run: |
          pip install --upgrade pip setuptools wheel --user
      - name: Install Dependencies
        run: |
          pip install -e .
      - name: Publish Release
        id: publish-release
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }} # use final when ready to publish
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        uses: ./.github/actions/publish-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          release_url: ${{ github.event.inputs.release_url }}
      - name: "** Next Step **"
        run: |
          echo "Verify the final release"
          echo ${{ steps.publish-release.outputs.release_url }}
          if [ ! -z "${{ steps.publish-release.outputs.pr_url }}" ]; then
             echo "Merge the forwardport PR"
             echo ${{ steps.publish-release.outputs.pr_url }}
          fi
