name: Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
jobs:
  # Run "pre-commit run --all-files"
  pre-commit:
    runs-on: ubuntu-20.04
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # ref: https://github.com/pre-commit/action
      - uses: pre-commit/action@v2.0.0
      - name: Help message if pre-commit fail
        if: ${{ failure() }}
        run: |
          echo "You can install pre-commit hooks to automatically run formatting"
          echo "on each commit with:"
          echo "    pre-commit install"
          echo "or you can run by hand on staged files with"
          echo "    pre-commit run"
          echo "or after-the-fact on already committed files with"
          echo "    pre-commit run --all-files"

  check-links:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup
        uses: ./.github/actions/common

      - name: Check Links
        uses: ./.github/actions/check-links

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ["3.7", "3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Install the Test dependencies
        run: |
          pip install -e .[test] codecov

      - name: Run the tests with coverage on Ubuntu
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          pytest -vv --cov jupyter_releaser --cov-branch --cov-report term-missing:skip-covered

      - name: Run the tests on Windows and macOS
        if: ${{ matrix.os != 'ubuntu' }}
        run: |
          pytest -vv -s

      - name: Verify the Generate Changelog Action
        if: ${{ matrix.os == 'ubuntu' }}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RH_REPOSITORY: jupyter-server/jupyter_releaser
          RH_BRANCH: master
          RH_SINCE: v0.3.0
          RH_UNTIL: v0.4.0
        run: |
          set -eux
          python -m jupyter_releaser.actions.generate-changelog
          cat CHANGELOG_ENTRY.md
          # Check for version entry in between the two versions and one outside
          cat CHANGELOG_ENTRY.md | grep -q "#95"
          cat CHANGELOG_ENTRY.md | grep -q "compare/v0.3.0...v0.4.0"
          # make sure it works with different settings
          export RH_SINCE=
          export RH_UNTIL=
          export RH_CONVERT_TO_RST=true
          sudo apt-get install pandoc
          pip install pypandoc
          python -m jupyter_releaser.actions.generate-changelog
          cat CHANGELOG_ENTRY.md

      - name: Coverage
        run: |
          codecov

  docs:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: jupyter_releaser_documentation
          environment-file: docs/environment.yml
          python-version: "3.9"
          auto-activate-base: false

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('docs/environment.yml') }}

      - name: Build docs
        run: |
          set -eux
          pip install .
          pushd docs
          make html
          popd
